# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d219f1c75e2edaf6f50ae7dfc59d559d4169d636c448b47c34bbb29837ed1436affa06fd62014147e46f9303c6e7af06bb02da742c1120aec36ac4ad2d8ef9da

test:
  secret_key_base: b7df5da01656cc83fe7b6983a2c772003c664ce644798dd48a3c4d3306a201052fcd39a212f423f84238693ee527541e00cf020df06416e132c8ef087646ba36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
